---
title: "Books"
date: "`r format(Sys.Date(), '%d %B, %Y')`"
output:
  github_document: 
    toc: yes
    toc_depth: 3
---

This is a collection of books I've found useful when learning about R, data visualization 
and econometrics. I've roughly grouped them by their main subject, however, 
the distinction is not meant to be that strict. This list will be extended 
whenever I find something new that is worth mentioning.

***

## Books related to visualization

1. Title: **The Elements of Graphing Data**     
   Author: William S. Cleveland    
   Year: 1994    
   Edition: 2    

1. Title **The Visual Display of Quantitative Information**  
   Author: Edward Tufte    
   Year: 2001  
   Edition: 2  

1. Title: **Visual Explanation: Images and Quantities, Evidence and Narrative**  
   Author: Edward Tufte  
   Year: 1997  
   Edition: 1

1. Title: **Show Me the Numbers - Designing Tables and Graphs to Enlighten**  
   Author: Stephen Few  
   Year: 2012  
   Edition: 2

***

## Books related to R

1. Title: **The Art of R Programming: A Tour of Statistical Software Design**  
   Author: Norman Matloff  
   Year: 2011  
   Edition: 1
   
   Description: This book is perfectly suited for those who already know some R
   and are not totally new to programming in general. As the book uses some more
   advanced terminology and covers topics that are probably not of interest to
   beginners (such as efficiency considerations or paralell computing) I'd recommend
   this book to all those who want to deepen their understanding of the language
   and take their experience up one level by getting systematic advice on how 
   to do things in R.
   
   
1. Title: **R for Data Science**  
   Author: Garrett Grolemund and Hadley Wickham  
   Year: 2016  
   Edition: 1  
   On the web: <http://r4ds.had.co.nz/>  
   
   Description: Although the book is still work in progress it looks extremly
   promising. The book covers all necessary steps involved in practical data 
   analysis: getting your data into R, tidy, transform, model and visualize it.

1. Title: **Advanced R**  
   Author: Hadley Wickham  
   Year: 2014  
   Edition: 1  
   On the web: <http://adv-r.had.co.nz/>

1. Title: **ggplot2**  
   Author: Hadley Wickham  
   Year: June 2016  
   Edition: 2
   
   Description: Systematically covers almost all aspects related to ggplot2.
   The book is for all those who want to understand the concept underlying ggplot2 
   instead of merly bunching together some lines of code.

1. Title: **R Cookbook**  
   Author: Paul Teetor   
   Year : 2011  
   Edition: 1  

1. Title: **R Graphics Cookbook**  
   Author: Winston Chang  
   Year : 2013  
   Edition: 1  
   On the web (excerpts): <http://www.cookbook-r.com/> 

1. Title: **Dynamic Documents with R and Knitr**  
   Author: Yihui Xie  
   Year : 2013  
   Edition: 1

***

## Books related to econometrics

1. Title: **Econometric Analysis**  
   Author: William Greene  
   Year: 2011  
   Edition: 7
   
1. Title: **Econometric Analysis of Cross Section and Panel Data**  
   Author: Jeffrey M. Wooldridge     
   Year: 2010      
   Edition: 2
   
1. Title: **Introductory Econometrics - A Modern Approach**  
   Author: Jeffrey M. Wooldridge     
   Year: 2015      
   Edition: 6

1. Title: **Mastering Metrics**  
   Author: Joshua Angrist and Jörn-Steffen Pischke    
   Year: 2015      
   Edition: 1
   
1. Title: **Mostly Harmless Econometrics**   
  Author: Joshua Angrist and Jörn-Steffen Pischke  
  Year: 2008  
  Edition: 1
